name: cpp11-501

on: [push]

jobs:
    build:         
        runs-on: ubuntu-latest
        environment: build
        container:
            image: feabhas/ubuntu-projects:latest
            options: -u 1001
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                sparse-checkout: solutions
                fetch-depth: 1     
            - name: build solutions
              run: |
                TOOLCHAIN=$(dirname $(find /opt/arm*/bin -name 'arm-none-eabi-gcc'))
                PATH="$TOOLCHAIN:$PATH"
                cp -r /home/feabhas/projects/cmake-target .
                cd cmake-target
                bash ./build.sh

